package Task2;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Themba Ntimane
 */
public class NumberGuesingGame extends javax.swing.JFrame {

    private int Score;
    private int attempts;
    private int randomNumber;

    private final int MAX_ROUNDS = 5;

    private void startNewGame() {
        Random random = new Random();
        randomNumber = random.nextInt(100) + 1; // Generate a random number between 1 - 100 and save it.
        attempts = 0;
        Score = 0; // Reset the score to 0
        JOptionPane.showMessageDialog(this, "You are have " + MAX_ROUNDS + " Rounds to Guess the number.");
        // Reset the fields
        lblMessage.setText("Welcome to Themba's Number Guessing Game");
        txtguessInput.setText(""); // Clear the input field
        lblScore.setText(" " + Score); // Update the score label
    }

    public NumberGuesingGame() {
        initComponents();
        startNewGame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        btnGuess = new javax.swing.JButton();
        btnPlayAgain = new javax.swing.JButton();
        txtguessInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number Guesing Game.");
        setBackground(new java.awt.Color(51, 102, 0));
        setName("frGuesingGame"); // NOI18N
        setType(java.awt.Window.Type.POPUP);

        lblMessage.setText("Welcome to Themba's Number Guesing Game");

        btnGuess.setForeground(new java.awt.Color(51, 102, 0));
        btnGuess.setText("Guess");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        btnPlayAgain.setForeground(new java.awt.Color(0, 102, 51));
        btnPlayAgain.setText("Play Again");
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAgainActionPerformed(evt);
            }
        });

        txtguessInput.setToolTipText("Guees any number from 1 - 100!!!");
        txtguessInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtguessInputActionPerformed(evt);
            }
        });

        jLabel1.setText("Score :");

        lblScore.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 102, 0), null));

        btnClose.setForeground(javax.swing.UIManager.getDefaults().getColor("nb.errorForeground"));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel2.setText("Number :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPlayAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtguessInput)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblMessage)
                        .addGap(106, 106, 106)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuess)
                    .addComponent(txtguessInput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayAgain)
                    .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtguessInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtguessInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtguessInputActionPerformed

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
// Get User Input
        String guestext = txtguessInput.getText();
// Exception Handling and Processing
        try {
            int userGuess = Integer.parseInt(guestext);
            attempts++;

            if (userGuess < 1 || userGuess > 100) {
                JOptionPane.showMessageDialog(this, "Please enter a number between 1 and 100.");
                txtguessInput.requestFocus();
                return;
            }

            if (userGuess == randomNumber) {
                JOptionPane.showMessageDialog(this, "Congratulations You have guessed the correct number in " + attempts);
                Score++;
                lblScore.setText("Your Current score is " + Score);
            } else if (userGuess > randomNumber) {
                JOptionPane.showMessageDialog(this, "Sorry you guessed a high number\n Try again!!");
            } else {
                JOptionPane.showMessageDialog(this, "Sorry you guessed a Low number\n Try again!!");
                txtguessInput.requestFocus();
            }
            if (attempts == MAX_ROUNDS) {
                JOptionPane.showMessageDialog(this, "Sorry, You have Reach Maximum Number per Session of your Rounds!!\n Final Score is " + Score);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please Enter a Valid Number.");
            txtguessInput.requestFocus();
        }
// Reset the fields Accordingly
        lblMessage.setText("Guess Another Number");
        txtguessInput.setText(""); // Clear the input field

    }//GEN-LAST:event_btnGuessActionPerformed

    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAgainActionPerformed
        startNewGame();
    }//GEN-LAST:event_btnPlayAgainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberGuesingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberGuesingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberGuesingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberGuesingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberGuesingGame().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblScore;
    private javax.swing.JTextField txtguessInput;
    // End of variables declaration//GEN-END:variables
}
